### ISSUE TITLE
CSSで画像のボタン化

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#11]
[この記事](https://saruwakakun.com/html-css/basic/box-shadow)を参考にyoutubeボタンを浮き上がらせて、ホバーすると沈むようにしたかったのですが、影が表示されません。導入方法を間違えてると思うのですが、どのようにしたらいいのでしょうか。
CSS
https://github.com/MOTOMUR/plz_donation/blob/f61254b910cc07a41e3e307f2a7ac1794b0d346c/src/views/components/YouTubeBtn.css#L1

導入したjs
https://github.com/MOTOMUR/plz_donation/blob/master/src/views/components/YouTubeChannelBtn.js

この呼び出しは現在myPageでのみの呼び出しです。

**Comment by karamari** [comment]
ソースを複数行貼り付けるには、始めの行をクリックしてから、shift を押しながら終わりの行をクリックするとできますよ。

CSS自体はできてると思います。
試したら影は表示されます。
https://jsfiddle.net/karamarimo/45j7bz5k/1/

import しているだけで、要素にクラスを指定していないですね。
スタイルを適用したい要素に今の場合`YouTubeBtn`クラスを指定する必要があります。

[Adding a Stylesheet](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-stylesheet)

**Comment by MOTOMUR** [comment]
要素指定してなかったのはどこにclass追加しても何も増えなかったからです。
今回影をつけてボタンっぽくしたいのはyoutubeiconの画像です。

aタグとimgタグdivのどこにcss入れたらいいのでしょう。。

**Comment by karamari** [comment]
> aタグとimgタグdivのどこにcss入れたらいいのでしょう。。

別にどれでもいいとは思います。
そもそも`div`で囲う必要がないのでは？

**Comment by MOTOMUR** [comment]
```
render(){
    return(
        <a class="YouTubeBtn" href={this.props.youtubeLink}><img src={YouTubeIcon} alt="" border="0" style={{width:'50px',height:'50px'}}/></a>
  )}
```
このようにしましたが、うまくいきません。。

**Comment by karamari** [comment]
先程のリンクを見ていただければ分かるように、jsxでは`class`ではなく`className`です。

**Comment by MOTOMUR** [comment]
そうでした申し訳ありません。

youtubeのアイコンを浮かしたかったのですが、これだと四角い枠になってしまうんですね。
角を丸くするやつだけではうまく綺麗に浮かせなさそうです。
<img width="368" alt="2017-12-02 18 08 15" src="https://user-images.githubusercontent.com/30742628/33513717-ccc8c210-d78b-11e7-835f-72fd27c0dac6.png">

こういう場合、画像自体をトリミングしたらいいでしょうか？
それとも画像の透明部分を認識して、浮かしたりできるんでしょうか？
今後twitterアイコンの設置も考えているので、どのようにやったらいいか教えてください。

**Comment by karamari** [comment]
`filter`の`drop-shadow`を使えばできるらしいです。
IEだと無理らしいですが。

[デモ](https://jsfiddle.net/karamarimo/6sbud52j/)

**Comment by karamari** [comment]
ちなみにそのYoutubeアイコンは少し古いやつですね。

[YouTube ロゴ](https://www.youtube.com/intl/ja/yt/about/brand-resources/#logos-icons-colors)
あ...「ドロップ シャドウなどの視覚効果を加える」のは禁止されてるようです...。

**Comment by MOTOMUR** [comment]
古いやつを引っ張って来てたのですね。訂正ありがとうございます。

ドロップシャドウの件ですが、
アイコンではなくロゴの方は禁止されていそうですが、アイコンは書かれていないから大丈夫ですかね？
特殊効果は禁止なようですが、これはそれに該当するのですかね？

**Comment by MOTOMUR** [comment]
youtubeブランドの使用についてを読んでいて思ったのですが、
今後追加するであろう、他のソーシャルメディアアイコンとの兼ね合いを考え、四角い形のyoutubeアイコンを使用することを検討中です。

ブランド使用の許諾が取れましたらまたここで報告します。

**Comment by karamari** [comment]
>ドロップシャドウの件ですが、
アイコンではなくロゴの方は禁止されていそうですが、アイコンは書かれていないから大丈夫ですかね？
特殊効果は禁止なようですが、これはそれに該当するのですかね？

https://www.youtube.com/yt/about/media/images/brand-resources/icons/YouTube-icon-common-errors.jpg
この真ん中のがまさに該当してるのでダメだと思います。

**Comment by MOTOMUR** [comment]
ほんとですね。。。
常に効果がついているではなく、ホバーしたら浮いたり暗くなったりもダメなんでしょうかね？

**Comment by karamari** [comment]
私には分からないので、問い合わせてみてはどうでしょうか。

**Comment by MOTOMUR** [comment]
そうですよね。申し訳ありません。問い合わせますね。

**Comment by MOTOMUR** [comment]
とりあえずこれについてはyoutubeの返信待ちですし、クローズしておきます。
