### ISSUE TITLE
YouTube Channelへのリンクデータをデータベースに追加する件。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#13]
youtube channelへのリンクの設定をuserのデーターベースに増やそうと思っているのですが、
データーベースのセキュリティの書き方をこれを機会に学ぼうと思います。
```
newData.val().matches(/^(ht|f)tp(s?):\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])*((0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\'\\/\\\\+&=%\\$#_]*)?$/)
```
このような構文はどのように調べたら出てくるでしょうか？

**Comment by karamari** [comment]
正規表現ですね。
どうせ  Youtube API などでも使うと思うのでチャンネルIDだけ保存すればいいような気もしますが...。

**Comment by karamari** [comment]
js の正規表現と異なる点もあるみたいなので公式ドキュメントに従って作るのがいいと思います。
[Firebase Security Rules Regular Expressions](https://firebase.google.com/docs/reference/security/database/regex)

**Comment by MOTOMUR** [comment]
> どうせ Youtube API などでも使うと思うのでチャンネルIDだけ保存すればいいような気もしますが...。

なるほど、cannelIDだけでの管理ができるようになる見込みもあるのですね。
機能的に早く盛り込みたい気持ちもありますが、youtubeAPIの進み具合を見て考えます。

正規表現と言うのですね。ありがとうございます。

**Comment by karamari** [comment]
チャンネルIDが分かれば`"https://www.youtube.com/channel/" + id`でurlは作れますし、cloud function からチャンネルに subscribe するときには ID を指定する必要がありますよね。

**Comment by karamari** [comment]
正規表現は英語で regular expression, 略して regex とも呼ばれます。

**Comment by MOTOMUR** [comment]
そうですよね。なるほど。
ではjs上でチャンネルへのリンクを作成する場合は
```
<YouTubeChannelBtn youtubeLink=""/>
```
ここのリンクに、"https://www.youtube.com/channel/" +データベースのチャンネルIDを渡すようにしたらいいですね。

regexはこれのことだったのですね。前に見たときに何だろうと思いながら放置してしまっていました。ありがとうございます。
