### ISSUE TITLE
AppBar IconElementRightについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#14]
ログイン、ログアウトボタンの横にセッティングのアイコンを設置し、そこにセッティングのルートを持たせようと思い、作成していたのですが、横並びになってもらえず困っています。どのようにしたら横に並べられるでしょうか？

**Comment by karamari** [comment]
とりあえずコードを載せてもらえますでしょうか。

**Comment by MOTOMUR** [comment]
```
<AppBar
          iconStyleRight={{display:'inline'}}
          title='plz donation'
          iconElementRight={
            <div style={{display:'inline'}}>
              <SettingIcon color="#FFFFFF"/><Switch>
                              <Route path="/login" />
                              <Route component={(this.state.userstate === false) ? SideLoginButton : LogoutBtn } />
                            </Switch>
            </div>
        }
          onLeftIconButtonTouchTap={() =>
            this.setState({ open: !this.state.open })}
        />
```
普通にスタイル挿入してもダメだったので、material uiのappbarを見て、右アイコンのスタイルがあることを知り、どちらもinlineとして見ましたがダメでした。

**Comment by karamari** [comment]
https://codesandbox.io/s/j7yxqwzol3
試してみたら普通に横並びになりました。

外側の`div`を`inline`にしても意味はないと思います。
おそらく`SettingIcon`か`Switch`が`display: block`になっているのではないでしょうか。

**Comment by MOTOMUR** [comment]
これでもかというほど、inlineを入れてみましたがうまくいきませんね。
Switchのせいかもしれませんね。

どうしたらいいでしょうか。
```
<AppBar
          iconStyleRight={{display:'inline'}}
          title='plz donation'
          iconElementRight={
            <div>
              <SettingIcon color="#FFFFFF" style={{display:'inline'}}/>
              <Switch style={{display:'inline'}}>
                <Route path="/login" />
                <Route style={{display:'inline'}} component={(this.state.userstate === false) ? SideLoginButton : LogoutBtn } />
              </Switch>
            </div>
        }
          onLeftIconButtonTouchTap={() =>
            this.setState({ open: !this.state.open })}
        />
```

**Comment by karamari** [comment]
デプロイしていただけますか。

**Comment by MOTOMUR** [comment]
デプロイしました。

**Comment by karamari** [comment]
`SettingIcon`が見当たらないですが...。

**Comment by MOTOMUR** [comment]
デプロイ自体はできていて、自分のブラウザでは確認できているので、キャッシュのせいではないでしょうか。

キャッシュのクリアをしないと反映しないことがよくありますので。

**Comment by MOTOMUR** [comment]
gitにということならばしていませんのでしておきます。

**Comment by karamari** [comment]
> デプロイ自体はできていて、自分のブラウザでは確認できているので、キャッシュのせいではないでしょうか。
キャッシュのクリアをしないと反映しないことがよくありますので。

そうでした。すみません。

**Comment by karamari** [comment]
https://github.com/MOTOMUR/plz_donation/blob/3ff6804cd38732e23ca40662e1b92804c50ffe42/src/components/LogoutBtn.js#L16-L22

https://github.com/MOTOMUR/plz_donation/blob/3ff6804cd38732e23ca40662e1b92804c50ffe42/src/components/SideLoginButton.js#L7-L13

LogoutBtnとSideLoginBtnが`div`で囲まれているからだと思います。
`div`はデフォルトで`display: block`なので。

`div`で囲む必要がそもそもないと思います。

これを修正すれば`display:'inline'`は不要だと思います。

**Comment by MOTOMUR** [comment]
ありがとうございます。横に表示されるようになりました。

ついでにで申し訳ないのですが、
<img width="1131" alt="2017-12-04 21 34 40" src="https://user-images.githubusercontent.com/30742628/33553159-fb1b238c-d93a-11e7-9b0c-3b38214e58be.png">
こんな感じでかっこ悪いので、大きさ変えようと思い、
```
iconElementRight={
            <div>
              <SettingIcon color="#FFFFFF" style={{marginRight:'10px'}}/>
              <Switch>
                <Route path="/login" />
                <Route component={(this.state.userstate === false) ? SideLoginButton : LogoutBtn } />
              </Switch>
            </div>
          }
```
ここの``` <SettingIcon color="#FFFFFF" style={{marginRight:'10px'}}/>```を
``` <SettingIcon color="#FFFFFF" style={{marginRight:'10px',width:'8%',height:'8%'}}/>```
と変えて大きさを調節したら、アイコンたちが中央めに配置されるようになり、ボタンとセッティングアイコンのセンターラインも揃えられません。

こういう場合はどのように解決するのでしょうか？verticalAlien:'center'をiconStyleRightに入れても上下のセンター揃えはうまくいきませんでした。

**Comment by MOTOMUR** [comment]
ついでになのですが、SVGアイコンを使って背景画面を作ろうと思って試してみていたのですが、どうしても他のオブジェクトに影響を与えてしまうので、影響しないように配置したいのですが、どのようにしたらいいでしょうか。例えばsettingページの例として、歯車アイコンの位置としては歯車の左半分が画面右から出ているように配置し、デザインしたいのですが、これはCSSやjsxで記述しないほうがいいのでしょうか？

現在の状態はこんな感じです。
```
<Card  style={{
                   width: 'auto',
                   margin: 'auto',
                   textAlign:'center',
                   verticalAlign:'Top',
                   backgroundColor:'#0097A7',
                   height:'600px'
                 }} >
            <CardTitle  title={
                          <h3>
                            Setting profile
                          </h3>
                        }

                        style={{
                          verticalAlign:'Top'
                        }}/>
            <CardText  style={{
                         width: 'auto',
                         margin: 'auto',
                         textAlign:'center'
                       }} >
              <TextField
                id="aaa"
                value={this.state.email}
                floatingLabelText="WAIT FOR FUNCTION"
                onChange={this.handleChange_email}
                />
              <RaisedButton
                label="Add"
                secondary={true}
                onClick={this.onYouTubeBtnClick}
                />
              <SettingIcon color="#FFFFFF" style={{textAlign:'right',marginRight:'10px',height:'100%',width:'100%'}}/>
            </CardText>

          </Card>
```

deploy、git
しておきますね。

**Comment by karamari** [comment]
どっちにも`vertical-align: middle`を付けたらこうなりました(サイズも適当に大きくしました)。

![plzdonation-56b64 firebaseapp com_makemypage](https://user-images.githubusercontent.com/33651188/33556516-82a3a2be-d947-11e7-813f-3aaa9dddd444.png)

**Comment by karamari** [comment]
背景を Card で作ろうとしているのはなぜでしょうか？

**Comment by MOTOMUR** [comment]
middleでしたか、textAlignに引っ張られてcenterでやっていました。
（どちらにも入れてはなかったので、どちらにせよできてなかったと思います。）
助かりました、ありがとうございます。

> 背景を Card で作ろうとしているのはなぜでしょうか？

特にこだわりはないです、textFieldがあるsignupPageから適当にコピペしてきたままになってしまっているだけですね。
Cardの状態では無理なことであれば変更いたします。

面倒臭いかもしれないことをお聞きしますが、現在、セッティングページを
ボトムナビゲーションの押されたところ、にページが変わるようになっているのですが、
ページ遷移のとき、cssで背景の歯車と青色がアニメーションで真ん中から左右に（歯車は左へ、青色は右へ）徐々に現れながら移動するといった記述は可能なのでしょうか？
（アニメーション機能を追加できることは知っているのですが、背景にそのような動きはできるんでしょうか？）

**Comment by karamari** [comment]
> セッティングページを
ボトムナビゲーションの押されたところ、にページが変わるようになっているのですが、

すみませんが意味がよく分かりません。
ボトムナビゲーションとはどれのことでしょうか？

>cssで背景の歯車と青色がアニメーションで真ん中から左右に（歯車は左へ、青色は右へ）徐々に現れながら移動するといった記述は可能なのでしょうか？

青色とはなんでしょうか？

svg のアニメーションはやろうと思えばいくらでもできます。
私も詳しいことは知りません。

http://www.hongkiat.com/blog/svg-animations/

**Comment by MOTOMUR** [comment]
> ボトムナビゲーションとはどれのことでしょうか？

セッティングページの下にあるタブっぽいやつです。

> 青色とはなんでしょうか？

背景色です。
可能ならば、歯車の左半分によって背景色の右側が切り取られている状態のものが良いです。

こういう切り取られたパターンは外部で用意してimgとして取り入れた方がいいのでしょうか？

svgやcssのアニメーションについては、僕もいろいろサイトを漁ってみようと思います。

**Comment by MOTOMUR** [comment]
アニメーション等は僕が頑張ります。

ところで基礎的な話として、背景を指定する方法は`backgraund-image`  `background-color`以外にあるでしょうか？`

**Comment by karamari** [comment]
イメージができていないのですが、歯車が左に移動すれば、右半分が画面に表示されるのではないですか？
青色というのはどういう形なのでしょうか。

できれば図を描いていただければ分かり易いのですが...。

**Comment by MOTOMUR** [comment]
![default](https://user-images.githubusercontent.com/30742628/33559156-3fa6c1a0-d94f-11e7-875d-dcc0572bea32.jpg)

とっても適当な絵で申し訳ないですが、この左の歯車に切ってあるレイアーと同じ色で枠が塗ってある歯車がrgbaのaの値を大きくしながらフェードインして行くようなイメージです。

青色というのは、現在のプロジェクトのアプリバーと同じ色です。
絵でいう黒に対応しています。

**Comment by karamari** [comment]
切り取られたような形は、単に白い歯車を被せればいいのではないでしょうか。

> 背景を指定する方法はbackgraund-image background-color以外にあるでしょうか？`

それらは独立に指定でき、どちらかを指定するというわけではありません。
他にもいくつかプロパティがありますが、`background`でまとめて指定できます。
詳しくは [background - CSS | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/background)

**Comment by MOTOMUR** [comment]
ありがとうございます。

ところでbackground-imageについて、前から思っていることがあるのですが、これの値はURLでしか与えられないのでしょうか？
ファイルにインポートした画像やアイコンはこれの値とすることはできないのですか？？

**Comment by karamari** [comment]
[Adding Images, Fonts, and Files](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files)

ここにあるように、画像ファイルへの相対パスを指定することができると思います。

**Comment by MOTOMUR** [comment]
ありがとうございます。

**Comment by MOTOMUR** [comment]
使いたいアイコンの保存場所が`import SettingIcon from 'material-ui/svg-icons/action/settings'`
となっていますが、これの相対パスは`material-ui/svg-icons/action/settings`でいいのでしょうか？

**Comment by karamari** [comment]
それは相対パスではなくパッケージのファイルを指定してますが、たぶんできるんじゃないでしょうか。
