### ISSUE TITLE
sideNavでのhistory.push

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#16]
sadeNavファイルに`this.props.history.push('/setting')`とすると、できないと言われるのですが、これがリンクの元のページだからでしょうか？
このようなファイル上ではどのようにパスを設定したらいいでしょうか？

**Comment by karamari** [comment]
できないと言われるというのは、具体的にどのようなエラーでしょうか。

**Comment by MOTOMUR** [comment]
このようなエラーです
`TypeError: Cannot read property 'push' of undefined
SideNav._this.settingClick
src/components/SideNav.js:55
  52 | };
  53 | 
  54 | settingClick=()=>{
> 55 |   this.props.history.push('/setting')
  56 | }
  57 | 
  58 | handleClose = () => this.setState({ open: false })`

**Comment by karamari** [comment]
`history`が`undefined`になっているってことですよね。

`history`が`props`として渡されるのは`Route`に指定したcomponentだけです。

それ以外で利用したい場合は`withRouter`を使うとできると思います。

[withRouter - React Router](https://reacttraining.com/react-router/web/api/withRouter)

**Comment by MOTOMUR** [comment]
ありがとうございます。遷移できるようになりました。
