### ISSUE TITLE
ブラウザ設定言語で、ページの言語設定。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#19]
ブラウザで設定している言語環境を参照して、ページを日本語表記するか英語表記するようにしたいです。
https://www.tam-tam.co.jp/tipsnote/program/post6940.html
こちらのサイトを参考にこんなことできるんだなと思いましたが、PHPで書かれているため、JSでの理解ができませんでした。

また、全ページ一貫して、日本語、英語の切り替えを保持するにはどのように記述するのでしょうか？
色々なサイトを見てましたが、JQueryを使用したものが多いのですが、ないとできないでしょうか？

**Comment by karamari** [comment]
もちろんjQueryなしでもできます。jQuery も所詮ライブラリですから、jQuery にしかできないことは存在しません。

たとえば react 用の localization library でこれがあります。
[react-localization](https://github.com/stefalda/react-localization)

**Comment by MOTOMUR** [comment]
ありがとうございます。無事に多言語化できました。
