### ISSUE TITLE
(design)Add logo-Icon 「ファビコン等の作成について」

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#2]
Now we can handle this site but designing is not readable,  I wanna know on what design tools you, making webSite, design. 
(It is better i can select color on like RGBA, what I can use absolutely same color on my website ) 

アイコンや、ページデザインのためのサイトを探すのに困っています。
カラー選択がしやすく（Webページで使っている色と全く同じ色を選択できるのが好ましい）、
ノンデザイナーがデザインするのに苦労しない UIのオススメがあれば教えて欲しいです。

**Comment by karamari** [comment]
@MOTOMUR 
Material UI を使っているので、faviconもマテリアルデザインにすればいいのでは？

例えば、オンラインでマテリアルデザインのアイコンを作れるサイトがあります。

- [Material Icon Generator](https://android-material-icon-generator.bitdroid.de/)(商用は有料)
- [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/index.html)

ページデザインというのは？Material UIだけで作れませんか？

**Comment by MOTOMUR** [comment]
＞ページデザインというのは？
ごめんなさい多分ページデザインという表現が違うのかもしれないですね。
例えば、[テラテイルのチュートリアル](https://teratail.com/tour)だと、Material uiのみで作成できると思うのですが、

いい例があまり見つかりませんでしたが、例えば[firebaseのチュートリアル](https://firebase.google.com/)の複雑な問題を解決にあるイラストのようなものや、
黄色やオレンジの背景のようなものはMaterial UIではなく事前に用意したファイルを読み込むか何かをすると思うのです。

このようなものを作るときにどのようなものを使うのかということを知りたいのです。

**Comment by MOTOMUR** [comment]
追記ですが、イラストや背景のようなデザインを自力でするよりも委託の方がいい場合もあるかもしれないですが、karamarimoさんならどのようにデザインをどうするかという問題を解決しますでしょうか？

**Comment by karamari** [comment]
私は（今のところ）趣味でプログラミングをやってるだけなので、残念ながらビジネス的なことはアドバイスできません（というか知識がありません）。

自分でやるなら、ウェブ上で探して良いのを見つけようとしますね。作れるものはできるだけ自分で作ります。

無料のクリップアートを提供しているサイトもあります。
[15 Places to Find Free Clipart](https://turbofuture.com/internet/Where-to-Find-Free-Clipart-The-15-Best-Places-for-Free-Clipart)

マテリアルデザインぽいサイトにするなら、背景も単純なものになると思うので、自分で作るという手もあります。背景は一色でもいいと思いますし、実際そのようなサイトはたくさんあります。

とりあえずいろんなデザインのサイトを見て、インスピレーションを得てみてはどうでしょうか。
[50+ Best illustration based websites for Inspiration](https://cssauthor.com/illustration-based-websites/)

**Comment by MOTOMUR** [comment]
わかりました。ありがとうございます。紹介してくださったサイト参考にさせていただきます。

**Comment by MOTOMUR** [comment]
とりあえず暫定のファビコンを作ってみたのですが、ローカル環境ではファビコンの表示ができているのですが、deployしてある方は表示できていません。
publicやbuildのファビコンの設定は全ていじったと思うのですが。どうしたらいいでしょう。

**Comment by karamari** [comment]
こちらでデプロイしてあるのを見たらfaviconは更新されてます。

> publicやbuildのファビコンの設定は全ていじったと思うのですが。どうしたらいいでしょう。

buildフォルダ内のファイルを自分で編集することはまずないと思います。
そういえば build フォルダは gitignore したほうがいいと思います。

**Comment by MOTOMUR** [comment]
ありがとうございます。

gitignoreしておきます。
