### ISSUE TITLE
iconElementLeftについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#20]
また同じような問題で申し訳ないですが、過去のを参考にしましたが、手詰まりです。
アイコンを中央揃えにしようと思い、
```
style={{verticalAlign:'middle'}}
          titleStyle={{verticalAlign:'middle'}}
          iconStyleLeft={{verticalAlign:'middle'}}
          title='plz donation'
          iconElementLeft={
            <span>
              <ListIcon color="#FFFFFF" onClick={this.listBtnClick} className="settingIcon"/>
              <HomeIcon color="#FFFFFF" onClick={this.homeBtnClick} className="settingIcon"/>
            </span>
          }
```
このように全ての要素に`verticalAlign:'middle'`を加えて見ましたが、中央で揃ってくれません。
どのように改善したら良いでしょう？

**Comment by karamari** [comment]
それはどの要素の属性でしょうか？

**Comment by MOTOMUR** [comment]
AppBarです。
sidenav.js内のappbarですが、gitは最新でないので更新します。デプロイは完了しています。

**Comment by karamari** [comment]
[公式の例](http://www.material-ui.com/#/components/app-bar)を真似て`IconButton`を使ったら勝手に中央揃えになりました。
https://codesandbox.io/s/j7yxqwzol3

**Comment by MOTOMUR** [comment]
ありがとうございます。左右で仕様が違うとはしりませんでした。

**Comment by karamari** [comment]
仕様が違うかどうかは分かりません。
`ListIcon`や`HomeIcon`はおそらくボタンとして配置していると思うので、どちらにせよ`IconButton`で囲ったほうがいいと思います。
右側の`SettingIcon`もそうですね。
