### ISSUE TITLE
GAEについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#21]
Google App Engineについて軽く調べて見たのですが、
ウェブの公開する場所をfirebaseからGAEに全て移行するという話でしょうか？
それともcloudfunctionsでやらせるはずだった機能をここに載せて、firebaseのサイト側から引っ張って使用するということでしょうか？

**Comment by karamari** [comment]
別にどちらでもできますが、static な部分(react app)は firebase で host するのが楽だと思います。

**Comment by MOTOMUR** [comment]
スタートアップを進めて行こうと思いますが、firebaseDatabaseトリガーだった関数はどのようにトリガーしたらいいでしょうか？DatabeseによってHTTPトリガーを発生させたりしたらいいのでしょうか？方法はどのようにしたらいいでしょう？？

**Comment by karamari** [comment]
cloud function で database の更新を GAE に知らせればいいのではないでしょうか。

**Comment by karamari** [comment]
GAE ではそれを受けて hub に subscribe リクエストを送ります。

また、GAE は hub から登録の確認や更新リクエストが来たら、firebase の database にアクセスして subscribe すべきかを判断し、hub にリクエストを返します。feed が送られてきたら database に書き込みます。

**Comment by karamari** [comment]
GAEは nodejs 以外の言語もサポートしているので好きな言語を使ってください。

**Comment by MOTOMUR** [comment]
GAEにて使うプロジェクトはreactappの方ではなく、cloudfunctionsの方のプロジェクトを使ってデプロイしたらいいですよね？

**Comment by karamari** [comment]
別の node プロジェクトにするのがいいと思います。

```
- root directory
-- firebase (現在の root directory)
-- app engine
```

**Comment by karamari** [comment]
上のような構成にするなら、もちろん`.git`は新しい root directory に置いてください。

なぜ分けるかというと、`package.json`にて依存するライブラリなどを管理するわけですが、GAE と firebase で `package.json`を共有するのは不自然だからです。

**Comment by karamari** [comment]
不自然というか、デプロイ時にGAEのサーバーは`package.json`に書かれているライブラリをダウンロードするので、GAEで使わないライブラリが含まれていると無駄になってしまうということですね。firebase も同様です。

**Comment by MOTOMUR** [comment]
わけてみました。不具合なさそうでしょうか？

**Comment by karamari** [comment]
`/gae-node/nodejs-docs-samples`が変なアイコンになってますが、中にさらに`.git`が入ってますか？

**Comment by MOTOMUR** [comment]
入ってますねきっと。
とりあえず使い方もよくわからないので、これからチュートリアルをやってみるところです。git cloneで取ってきたので多分それですね。
消したほうがいいでしょうか？

**Comment by MOTOMUR** [comment]
そういえば、 GAEでHTTPトリガーの関数を作るとき、何を使ったらいいですか？
元々はfirebaseでやろうとしてたと思うんですけど、node.jsとExpressだけでやろうとしていることはできるでしょうか？

**Comment by MOTOMUR** [comment]
https://firebase.google.com/docs/functions/use-cases#other_ways_to_integrate_with_third-party_services_and_apis
ここの

> Realtime

 Database 書き込みで webhook にリクエストを送信します。

https://github.com/firebase/functions-samples/tree/master/minimal-webhook
これを用いてリクエストを送って、それをGAEで受け取ればよいのでしょうか？

**Comment by karamari** [comment]
> 消したほうがいいでしょうか？

私もよく知らないですが普通gitはネストしないと思うので消したほうがいいと思います。

> GAEでHTTPトリガーの関数を作るとき、何を使ったらいいですか？

一応、GAEにはトリガーなどの概念はありません。全部自分でやります。
といっても express などを使えば、自分がコーディングするのはほぼ middleware だけですが。
nodejs ならやはり定番は express ですね。

> https://github.com/firebase/functions-samples/tree/master/minimal-webhook
これを用いてリクエストを送って、それをGAEで受け取ればよいのでしょうか？

用いてというか参考にすればできると思います。
