### ISSUE TITLE
settingのプロフィール編集機能。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#22]
settingページにプロフィールの設定機能を追加したいのですが、パーミッションdenyedとなってしまいます。
ルールを通せる状態ではないのでしょうか？
一応、hasChildrenは通れるようにコードを書いたつもりですが。

https://github.com/MOTOMUR/plz_donation/blob/ca736cf7705a0a034b08550162436070e5702122/src/views/Setting.js#L100-L116
このようにしています。

**Comment by karamari** [comment]
値は大丈夫ですか？

`set`ではなく`update`の方がいいと思います。
そうすれば`userStar`を取得する必要もなくなりますし、`uid`を更新する必要もありませんよね。

**Comment by MOTOMUR** [comment]
https://github.com/MOTOMUR/plz_donation/blob/9d37d4952e765e5a61fad13c7d16cbcb6097620b/src/views/Setting.js#L100-L110
このようにしましたがダメです。
<img width="1629" alt="2017-12-12 23 36 00" src="https://user-images.githubusercontent.com/30742628/33890001-3fc09d18-df95-11e7-9c3c-9fb42d64175a.png">
データはこのように三つあります。他も設定しなければまずいですかね？どのように設定したらいいでしょう？

**Comment by karamari** [comment]
一度これでやってみてもらえますか？
```js
firebase.database().ref('users/' + this.state.usreId).update(editData) 
```

**Comment by karamari** [comment]
現在の security rules は https://github.com/MOTOMUR/plz_donation/issues/15#issuecomment-348966229 と同じですよね？

**Comment by MOTOMUR** [comment]
makeMyPageが治ったので、こちらもいけると思ったのですが、こちらはまだうまくいきませんね。

update時に編集対象じゃないデータのwriteが引っかかって、書き込めないとかあるのですかね？

userStarは無条件で`update(){true}`としてもダメだったので、
```
path /users {
  read(){auth!=null}
  /{uid} is User {
    /user {
      create(){auth != null && this.parent().uid == auth.uid}
      update(){auth != null && auth.uid == uid }
    }
    /explain {
      create(){auth != null && this.parent().uid == auth.uid}
      update(){auth != null && auth.uid == uid }
    }
    /profile_image {
      create(){auth != null && this.parent().uid == auth.uid}
      update(){auth != null && auth.uid == uid }
    }
    /uid {
      create(){auth != null && this == auth.uid}
      update(){auth != null && auth.uid == uid && prior(this) == this}
    }
    /youtubeChannel {
      create(){auth != null && this.parent().uid == auth.uid}
      update(){auth != null && auth.uid == uid }
    }
    /user_posts {
      create(){auth != null && this.parent().uid == auth.uid}
      update(){auth != null && auth.uid == uid }
    }
    /starred_users {
      create(){auth != null && this.parent().uid == auth.uid}
      update(){auth != null && auth.uid == uid }
    }
    /userStar {
    }
  }
}
```
この辺りがまずいんでしょうかね？
お力をお貸しください。

**Comment by karamari** [comment]
> update時に編集対象じゃないデータのwriteが引っかかって、書き込めないとかあるのですかね？

それはないと思います。

**Comment by karamari** [comment]
データベースでそのユーザーの`uid`フィールドは正しい値になってますか？

今の問題とは関係ないですが`this.parent().uid == auth.uid`は`uid == auth.uid`でいいのでは？

**Comment by MOTOMUR** [comment]
> this.parent().uid== auth.uidはuid == auth.uidでいいのでは？

そうですね。直してみました。
いろいろ確認してみたのですが、誤字でuserIdがusreIDになってました。。。。。
ありがとうございます！
