### ISSUE TITLE
☣️GAEのLogについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#27]
ログの内容がわからないものについて、教えていただきたいと思います。
`Error: No default engine was specified and no extension was provided. at new View (/app/node_modules/express/lib/view.js:61:11) at Function.render (/app/node_modules/express/lib/application.js:570:12) at ServerResponse.render (/app/node_modules/express/lib/response.js:971:7) at /app/app.js:165:7 at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5) at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) at /app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) at next (/app/node_modules/express/lib/router/index.js:275:10) at /app/app.js:154:3`
定期的にこれは表示されているのですが、これは何がまずいでしょう？

また、youtubeから受け取ったものがこのように複数表示されるのですが、
`[0mGET /recieve_new_video_data?id=123&hub.topic=https://www.youtube.com/xml/feeds/videos.xml%3Fchannel_id%3DUC9PrC6oeRWNbsFwjzY8AaQg&hub.challenge=17130545588432292704&hub.mode=subscribe&hub.lease_seconds=1 [33m404 [0m0.704 ms - 136[0m`

`0mGET /recieve_new_video_data?id=sometimesPushSubscribe&hub.topic=https://www.youtube.com/xml/feeds/videos.xml%3Fchannel_id%3DUC9PrC6oeRWNbsFwjzY8AaQg&hub.challenge=14438744212197449253&hub.mode=subscribe&hub.lease_seconds=1 [33m404 [0m0.488 ms - 136[0m`

`[0mGET /recieve_new_video_data?id=prevYoutubeChannelDelete&hub.topic=https://www.youtube.com/xml/feeds/videos.xml%3Fchannel_id%3Da&hub.challenge=14622750458852670948&hub.mode=unsubscribe [33m404 [0m4.833 ms - 136[0m`

`[0mGET /recieve_new_video_data?id=123&hub.topic=https://www.youtube.com/xml/feeds/videos.xml%3Fchannel_id%3DUC9PrC6oeRWNbsFwjzY8AaQg&hub.challenge=14656456789216690719&hub.mode=subscribe&hub.lease_seconds=1 [33m404 [0m0.885 ms - 136[0m`

こんな感じでいっぱいくるので解読が大変ですね。

<img width="1311" alt="2017-12-22 18 04 19" src="https://user-images.githubusercontent.com/30742628/34292058-94b6f40c-e742-11e7-87f5-7cfcb82e73c1.png">
この写真の上の４つが、上のコードの４つと同じなんですが、この写真の下の４つ（特殊な
GETとか書いてあるやつ）と、写真の上のやつは同じものですか？

**Comment by MOTOMUR** [comment]
それと、見つけるの苦手なので、かなり派手にconsole.logの中身をアレンジしたのですが、あまり反映されないんですけど、
`console.log("!-!-!-!-!-!-!-!-ANOTHOR_SUBSCRIBE_ERROR-!-!-!-!-!-!-!-!" + err);`
こんな感じの書き方は見えないんですかね？

最新のデプロイしても、昔の内容が残ってる部分とかもあるんですが、なんかデプロイする際に消したりしたほうがいいんですかね？

**Comment by karamari** [comment]
> 最新のデプロイしても、昔の内容が残ってる部分とかもあるんですが、なんかデプロイする際に消したりしたほうがいいんですかね？

versions のところを見たら複数 version がないですか？

**Comment by karamari** [comment]
> それと、見つけるの苦手なので、かなり派手にconsole.logの中身をアレンジしたのですが、あまり反映されないんですけど、

そのコードが実行されていないのではないでしょうか。

> この写真の上の４つが、上のコードの４つと同じなんですが、この写真の下の４つ（特殊な GETとか書いてあるやつ）と、写真の上のやつは同じものですか？

分かりません。そのログは morgan によるものだと思うんですが、文字化けしているのは色付きで出力しているからかもしれません。

**Comment by karamari** [comment]
> No default engine was specified and no extension was provided

https://stackoverflow.com/questions/23595282/error-no-default-engine-was-specified-and-no-extension-was-provided
html を返すコードが残ってませんか？

**Comment by MOTOMUR** [comment]
> versions のところを見たら複数 version がないですか？

firebaseと違って、違うバージョンも保存されているんですね。消去しました。ありがとうございます。

> そのコードが実行されていないのではないでしょうか。

そのようですね。コード直してみます。

文字化けは、色付き文字でしたね。

> html を返すコードが残ってませんか？

直してみます！

**Comment by MOTOMUR** [comment]
全くログに表示したい部分のログが表示されないので、
```
app.get('https://for-cloud-function.appspot.com/recieve_new_video_data', function (req, res, next) {
  console.log('!-!-!-!-this is req body (get)-!-!-!-!' + req.body);
});
app.post('https://for-cloud-function.appspot.com/recieve_new_video_data', function (req, res, next) {
  console.log('!-!-!-!-this is req body (post)-!-!-!-!' + req.body);
});

push.on("notification", function (item) {
    console.log("notification");
    console.log('~~~~~~~~~~~~~~~~~~~~~~notification~~~~~~~~~~~~~~~~~~~~~~~')
    console.log('!-!-!-!-this is notification item-!-!-!-!' + item)
    console.log('~~~~~~~~~~~~~~~~~~~~~~item~~~~~~~~~~~~~~~~~~~~~~~')
    var self = this
```

こんな感じで、どれか実行されてくれないかと増やして見たのですが、どれも実行されません。
リクエストの受け取りに対する理解がまだ浅いので、何がダメかわかりません。

**Comment by karamari** [comment]
> `app.get('https://for-cloud-function.appspot.com/recieve_new_video_data'`

いやドメインのところは要らないですよ...。
`app.get('/recieve_new_video_data'`

**Comment by MOTOMUR** [comment]
```
app.get('/recieve_new_video_data', function (req, res, next) {
  console.log('!-!-!-!-this is req body (get)-!-!-!-!');
  console.dir(req.body)
});
```
このようにしたら実行されるようになりました。
しかし、console.dirの中身のログがよくわかりません。
<img width="1307" alt="2017-12-27 1 36 55" src="https://user-images.githubusercontent.com/30742628/34360695-761dd530-eaa6-11e7-9b95-7716891769e1.png">
このような感じで中身は観れたのですが。。。

**Comment by karamari** [comment]
それは hub から送られてきたデータですか？

**Comment by MOTOMUR** [comment]
ごめんなさいわからないです。
送信先やデータの内容ってどのようにしたらわかりますか！？

**Comment by karamari** [comment]
心当たりがないのでしたら hub からのリクエストだと思いますね。

その labels や recource timestamp は GAE が自動的に付与したデータだと思いますが、一つ前のログと比較して見るとどこが自分で出力したデータか分かるのではないでしょうか。

**Comment by MOTOMUR** [comment]
<img width="1318" alt="2017-12-28 23 22 34" src="https://user-images.githubusercontent.com/30742628/34413329-05c115c8-ec26-11e7-9d23-68d94528f951.png">
getで受け取ったデータはこの部分だと思います。
notificationは動作してないみたいです。
僕のコードを見ていただくとわかると思います。
```
app.get('/recieve_new_video_data', function (req, res, next) {
  console.log('!-!-!-!-this is req body (get)-!-!-!-!');
  console.dir(req.body)
  push.on("notification", function (item) {
      console.log("notification in getfunc");
      console.log('~~~~~~~~~~~~~~~~~~~~~~notification in getfunc~~~~~~~~~~~~~~~~~~~~~~~')
      console.log('!-!-!-!-this is notification in getfunc item-!-!-!-!' + item)
      console.log('~~~~~~~~~~~~~~~~~~~~~~item~~~~~~~~~~~~~~~~~~~~~~~')
      var self = this
    })
});
```
push.onをgetの中に入れたのは、入れてなくても動作しなかったためです。
再購読のデータは送られてきてないのですかね？leasesecondを30にしてるので30秒後に再購読のリクエストが、ここに届くと思うのですが。

**Comment by karamari** [comment]
> push.onをgetの中に入れたのは、入れてなくても動作しなかったためです。

いや、中に入れる理由がよく分からないですが...。
リスナーが増えるだけではないでしょうか。

購読確認/更新は notification イベントではないと思います。
また、`hubabuba`を使っている限り購読確認/更新は自動でやってくれると思います。

インスタンス数が1つでないとややこしいことになるのでとりあえずそのように設定してみてください。
https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml

**Comment by MOTOMUR** [comment]
> 購読確認/更新は notification イベントではないと思います。

そうなんですね。勘違いしてました。再購読はコーディングしないでもいいんですね？

設定しました。resourcesのcpu等の設定は適当でいいんですかね？現在、例のようにして見てますが。

**Comment by karamari** [comment]
それはリクエストの量に応じて設定する必要があります。

**Comment by MOTOMUR** [comment]
なるほどです。

**Comment by MOTOMUR** [comment]
<img width="1296" alt="2018-01-09 11 02 29" src="https://user-images.githubusercontent.com/30742628/34701627-abc7aae0-f52c-11e7-8332-6ba18aa0d760.png">
このようなエラーが発生するようになってしまいました。

エラーを検索すると、xml系のエラーなようですが、どのように直していいかわからないので教えて欲しいです。

該当部：
https://github.com/MOTOMUR/plz_donation/blob/d783195da76076f047bb9acd551a795b34399d6e/gae-node/app.js#L148-L155

**Comment by karamari** [comment]
`req.body`の中身はなんでしょうか？

**Comment by MOTOMUR** [comment]
表示の前にさっきのエラーを吐くので中身の確証はありませんが、
https://developers.google.com/youtube/v3/guides/push_notifications
ここのxmlだと思います。

textpayloadは{}のみ表示されています。

**Comment by karamari** [comment]
"Text data outside of root node"というエラーは xml2js によるエラーなので、その前の`console.dir(req.body)`でログされるはずなんですが...。もしかすると`console.dir`には対応していないのかもしれません。

```js
console.log(JSON.stringify(req.body))
```
としてみてはどうでしょうか。

**Comment by karamari** [comment]
とりあえず`console.log(JSON.stringify(req))`で`req`の内容を確認してみるのもいいと思いますが。

**Comment by karamari** [comment]
もしかしたら直接`console.log(req)`したほうがきれいな出力になるかもしれません。

**Comment by MOTOMUR** [comment]
もしかしてですが、
コールバックURLのところは、
https://github.com/stavinski/hubabuba/blob/1cf3d5d729b80411988b213ec934b863c7450a72/examples/index.js#L82-L85
こうして、
https://github.com/stavinski/hubabuba/blob/1cf3d5d729b80411988b213ec934b863c7450a72/examples/index.js#L3-L10
こうするんですかね？

今更気づきましたが、hubabubaのexampleはexpressじゃなくてconnect使ってますね。

**Comment by karamari** [comment]
あ、そうですね。
https://github.com/stavinski/hubabuba#hubabuba
で

> The handling side uses connect so that you can plug it into an existing connect/express application.

と書いてあるので express にも使えると思います。

**Comment by MOTOMUR** [comment]
つまり今回のアプリの場合はcallbackは

```
var connect = require("connect")
  , http = require("http")
  , url = require("url")
  , Hubabuba = require("hubabuba")
  , push = new Hubabuba("https://for-cloud-function.appspot.com:3000/hubabuba", {
      debug : true
    });
```
これが正しいのですか？

**Comment by karamari** [comment]
いえ`connect`はいらないですしurlもそれでなくてもいいと思います。

**Comment by MOTOMUR** [comment]
https://github.com/stavinski/hubabuba/blob/1cf3d5d729b80411988b213ec934b863c7450a72/examples/index.js#L82-L85
このようにポートは開かなくてもいいし、callbackUrlは`https://for-cloud-function.appspot.com/recieve_new_video_data`このようにして、
`app.get('/recieve_new_video_data')`でリッスンしたらいいという理解であってますでしょうか？

**Comment by karamari** [comment]
`hubabuba`は express のいち middleware として使用するということですから、ポートをリッスンするのは
https://github.com/MOTOMUR/plz_donation/blob/master/gae-node/bin/www
で既にやっていますので、もう一つする必要はありません。

> app.get('/recieve_new_video_data')でリッスンしたらいいという理解であってますでしょうか？

hub とのやりとりは hubabuba が自動的にやってくれるので必要ありません。

**Comment by MOTOMUR** [comment]
なるほど、ではなぜnotificationにデータが来ないかわからなくなってしまいました。
購読しているアカウントで動画投稿してもデータが来ません。

subscribe系はかけていると思うので、なんで来ないかが謎です。。。。

コールバックは
`https://for-cloud-function.appspot.com`
か
`https://for-cloud-function.appspot.com/recieve_new_video_data`
かどっちが良いのかわかってませんが。これはあまり関係ないですよね？

**Comment by karamari** [comment]
https://github.com/stavinski/hubabuba#example-usage
にあるように
```js
push.on("error", console.error)
    .on("subscribed", function (item) {
      console.log("subscribed");
    })
    .on("unsubscribed", function (item) {
      console.log("unsubscribed");
    })
    .on("denied", function (item) {
      console.log("denied");
    })
    .on("notification", function (item) {
      console.log("notification");
})
```
として subscribe できているか確認してみてはどうでしょうか。

**Comment by karamari** [comment]
hubabuba はメモリ上に、subscribe している hub や topic を保持しているはずですが、デプロイするたびにプログラムは再実行されるので、そのデータは失われてしまいます。その状態で feed が来ると、hubabuba は subscribe していないところから来たとして無視する可能性があります。

**Comment by karamari** [comment]
すみませんソースを見たところそうではなさそうです。

**Comment by MOTOMUR** [comment]
やはり、push.onとしているところは全てデータが来ていません。

コールバックの設定がよくないのでしょうか？
正直もう何がダメかわからないです。
https://for-cloud-function.appspot.com/
これと、https://for-cloud-function.appspot.com/new_video_recieveはダメっぽかったです。

**Comment by karamari** [comment]
https://github.com/MOTOMUR/plz_donation/blob/d783195da76076f047bb9acd551a795b34399d6e/gae-node/app.js#L33-L34

とりあえずこれはいらないので外してください。

```js
app.use(push.handler())
```
はしましたか？

**Comment by MOTOMUR** [comment]
`app.use(push.handler())`
抜けていました。。
これは何をするコードですか？

**Comment by karamari** [comment]
hubabuba は hub とのやりとりを自動でやってくれるわけですが、その機能をミドルウェアとして生成するのが`push.handler()`です。express の `app` にミドルウェアとして登録するのが`app.use()`です。

**Comment by MOTOMUR** [comment]
ミドルウェアとして動かし忘れていたのですね。notificationが来なかったのは納得です。
とりあえずデバックして様子見てみます。

**Comment by MOTOMUR** [comment]
<img width="833" alt="2018-01-13 0 09 23" src="https://user-images.githubusercontent.com/30742628/34881144-1247e21e-f7f6-11e7-89c6-35059fecfb63.png">
なぜか使っていない、app.setが怒られています。
```
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var connect = require("connect")
  , http = require("http")
  , url = require("url")
  , Hubabuba = require("hubabuba")
  , push = new Hubabuba("https://for-cloud-function.appspot.com/", {
      debug : true
    });

push.on("error", console.error)
    .on("subscribed", function (item) {
      console.log("subscribed");
    })
    .on("unsubscribed", function (item) {
      console.log("unsubscribed");
    })
    .on("denied", function (item) {
      console.log("denied");
    })
    .on("notification", function (item) {
    console.log("notification");
    console.log('~~~~~~~~~~~~~~~~~~~~~~notification~~~~~~~~~~~~~~~~~~~~~~~');
    console.log('!-!-!-!-this is notification item-!-!-!-!');
    console.log('~~~~~~~~~~~~~~~~~~~~~~item~~~~~~~~~~~~~~~~~~~~~~~');
    var self = this
    console.log(item)
    var result = convert.xml2json(item, {compact: true});
    console.log("おお");
    console.log(result);
            // admin.database().ref().child('temps').set({timestamp:admin.database.ServerValue.TIMESTAMP})
            // admin.database().ref('temps/timestamp').once("value",function(snapshot){
            //   self.setState({timestamp : snapshot.val()})
            // })
            // var newPostKey = admin.database().ref().child('posts').push().key;
            // var postData = {
            //   author: ,
            //   uid: ,
            //   body:,
            //   title:,
            //   post_image: ,
            //   postId: newPostKey,
            //   postStar: {
            //     starCount:0,
            //     stars:{}
            //   },
            //   postComment:{
            //     commentCount : 0,
            //     comments:{}
            //   },
            //   timestamp:self.state.timestamp
            // };
            // var updates = {}
            // updates['posts/' + newPostKey] = postData
            // updates['users/' + self.state.userId + '/user_posts/' + newPostKey]= true
            // return admin.database().ref().update(updates);
  })



var convert = require('xml-js');

var admin = require("firebase-admin");
var serviceAccount = require("./comllesns-firebase-adminsdk-ey038-fc21759826.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://comllesns.firebaseio.com"
});

const WEBHOOK_URL = 'http://requestb.in/1mqw97l1'

var app = express();

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(push.handler())


//this is subscription
admin.database().ref('/users/').on("child_changed",function(snapshot){
    var NewChannel_Id = snapshot.val().youtubeChannel
    var uid = snapshot.val().uid
    admin.database().ref('/youtubeChannels/').orderByChild('uid').equalTo(uid).once("value",function(snapshot) {
      if(snapshot.val()==null){
        var preYoutubeChannel = null
      }else{
        var channel = []
        channel = snapshot.val()
        for(var key in channel){
          var preYoutubeChannel = key
        }
      }
      if(NewChannel_Id != preYoutubeChannel && NewChannel_Id != null){
        if(preYoutubeChannel == null){
          push.subscribe({
                id: "FIRST-PushSubscribe",
                topic: "https://www.youtube.com/xml/feeds/videos.xml?channel_id=" + NewChannel_Id,
                hub: "https://pubsubhubbub.appspot.com",
              }, function handleSubscribing(err, item) {
              if (err) {
                var sty ="color:red;background-color:black;"
                console.log("!-!-!-!-!-!-!-!-FIRST_SUBSCRIBE_ERROR-!-!-!-!-!-!-!-!" + err, sty);
                return;
              }else{
                var sty ="color:black;background-color:blue;"
                console.log("firest_subscribed to %s", item.topic, sty);
                admin.database().ref('/youtubeChannels/' + NewChannel_Id).set({
                  subscriptionStatus:"SUBSCRIBED",
                  uid:uid
                })
              }
            });
        }else{
          push.unsubscribe({
                id: "prevYoutubeChannelDelete",
                topic: "https://www.youtube.com/xml/feeds/videos.xml?channel_id=" + preYoutubeChannel,
                hub: "https://pubsubhubbub.appspot.com",
              }, function handleSubscribing(err, item) {
              if (err) {
                console.log("!-!-!-!-!-!-!-!-UNSUBSCRIBE_ERROR-!-!-!-!-!-!-!-!" + err);
                return;
              }else{
                var sty ="color:blue;background-color:yellow;"
                console.log("unsubscribed to %s", item.topic ,sty);
                admin.database().ref('/youtubeChannels/' + preYoutubeChannel).set({
                  subscriptionStatus:null,
                  uid:null
                })
              }
            });
          push.subscribe({
                id: "sometimesPushSubscribe",
                topic: "https://www.youtube.com/xml/feeds/videos.xml?channel_id=" + NewChannel_Id,
                hub: "https://pubsubhubbub.appspot.com",
              }, function handleSubscribing(err, item) {
              if (err) {
                var sty ="color:black;background-color:red;"
                console.log("!-!-!-!-!-!-!-!-ANOTHOR_SUBSCRIBE_ERROR-!-!-!-!-!-!-!-!" + err, sty);
                return;
              }else{
                var sty ="color:black;background-color:blue;"
                console.log("anothor_subscribed to %s", item.topic ,sty);
                admin.database().ref('/youtubeChannels/' + NewChannel_Id).set({
                  subscriptionStatus:"SUBSCRIBED",
                  uid:uid
                })
              }
            });
        }
      }
    })
});

```

**Comment by karamari** [comment]
エラーが出てるのは bin/www の方ですよ。
https://github.com/MOTOMUR/plz_donation/blob/d783195da76076f047bb9acd551a795b34399d6e/gae-node/bin/www#L16

なぜエラーになったかというと、app.js で何も export していないからです。

https://github.com/MOTOMUR/plz_donation/blob/d783195da76076f047bb9acd551a795b34399d6e/gae-node/app.js#L163

この行を消してしまったのでは？

**Comment by MOTOMUR** [comment]
消しちゃってましたね。デバックしてみます。

**Comment by MOTOMUR** [comment]
https://github.com/MOTOMUR/plz_donation/blob/master/iOS/test.json
フォルダ場所iOSになってますが、GAEの方です。
youtubeからのfeedのxmlをjsonに変換したものなのですが、思うように中身を指定できません。

```
var matchChannelId = result.feed["yt:channelId"]._text
var VideoTitle = result.feed.title._text
```
これではダメなようです。（特にchannelID）
yt:が曲者で、うまく指定できません。
videotitleの部分はもしかしたらいけてるかもしれませんが。

アドバイスお願いします。

**Comment by karamari** [comment]
`result`は何ですか？

**Comment by karamari** [comment]
```js
var result = convert.xml2json(item.content, {compact: true});
```
ですね。`result.feed.entry["yt:channelId"]._text`では？

**Comment by MOTOMUR** [comment]
<img width="1299" alt="2018-01-13 18 41 40" src="https://user-images.githubusercontent.com/30742628/34904862-7216935c-f891-11e7-9b01-e7b74117bff7.png">

なぜかダメですね。push.onの中だからとかですかね。。。

**Comment by karamari** [comment]
どういうことでしすか？

**Comment by MOTOMUR** [comment]
「entryはないよ」といったようなログが出ます

**Comment by karamari** [comment]
いえ、「push.onの中だからとかですかね」とはどういうことでしょうか？

**Comment by karamari** [comment]
そのエラーだと`result.feed === undefined`ということになりますよね？`result`を出力してみてはどうでしょうか？

**Comment by MOTOMUR** [comment]
Hubabubaからのログっぽかったのでそう思ったのです。

先ほどのtest.jsonがリザルトの出力なので、効果的かはわかりませんが、result.feedを出力して見ます。

**Comment by MOTOMUR** [comment]
`var result = convert.xml2json(item.content, {compact: true});`が非同期処理な可能性はありますかね？
promiseしてデバックして見ていますが、同期、非同期どちらでしょうか。

**Comment by MOTOMUR** [comment]
```
var p0 = new Promise(
        return something
      )
      var pt0 = p0.then(
       // something　は存在しますか？
      )
```
プロミスにこのような書き方があるというのを見たのですが、使い方と理解は上記であってますでしょうか？

**Comment by karamari** [comment]
> var result = convert.xml2json(item.content, {compact: true});が非同期処理な可能性はありますかね？
promiseしてデバックして見ていますが、同期、非同期どちらでしょうか。

いや [docs](https://www.npmjs.com/package/xml-js)にそう書いてないのでそんなことはないと思いますよ。

> プロミスにこのような書き方があるというのを見たのですが、使い方と理解は上記であってますでしょうか？

違います。`new Promise`の引数に`return something`という statement が来るのはおかしいですよね。一度Promiseについて調べられたほうがいいかと思います。

```js
const p = new Promise(function (resolve, reject) {
  resolve(1)
})
const p2 = p.then(function (result) {
  // result === 1
})
```

**Comment by MOTOMUR** [comment]
どちらにせよpromiseは値がうまく取得できるようになったら、使うので、その時に確認して書いて見ます。

`result`の件ですが、連想配列のため、for (var key in result)にてkeyを取得してやらないと値の指定ができないのでしょうかね？
`result.feed`がundefinedとなったのでこう考えました。

**Comment by MOTOMUR** [comment]
for文で回して見ましたが、1文字ずつカットされたので、多分jsでは配列とみなしていません。json形式だからでしょうか？`xml2json`を使ってたので、`xml2js`にして試して見ます。

**Comment by MOTOMUR** [comment]
先ほどので解決できたので、promiseを学びつつコード書いていきます。

**Comment by karamari** [comment]
> json形式だからでしょうか？xml2jsonを使ってたので、xml2jsにして試して見ます。

あ...そうでした。`xml2json`はjson textに変換します。

**Comment by karamari** [comment]
> resultの件ですが、連想配列のため、for (var key in result)にてkeyを取得してやらないと値の指定ができないのでしょうかね？

key はわかっているので取得する必要はないです。

**Comment by MOTOMUR** [comment]
```
var p1 = new Promise(function(resolve){
        admin.database().ref('youtubeChannels/' + ChannelId).once('value').then(function(snapshot){
          uid = snapshot.val().uid
          resolve(uid)
        })
      })
      var pt1 = p1.then(function(resolve){
        console.log(uid)
        admin.database().ref('users/' + uid).once('value').then(function(snapshot){
          author = snapshot.val().user
          resolve(author)
        })
      })
      var pt2 = pt1.then(function(resolve){
        console.log("ああああああpt2 uid///////" + uid)
        console.log("ああああああpt2 author///////" + author)
//any function ....
})
```

このようにやって見ていたのですが、authorがundefinedとなってしまうので、同期的に処理できていないようですね。
firebase.database.refのような非同期関数（ここではadmin.database.ref）は処理し終わらないまま次のプロミスに行ってしまうのでしょうか？
どのように同期的にしたらよいでしょうか？

**Comment by MOTOMUR** [comment]
```
function fetchUid(ChannelId) {
  return new Promise(function(resolve, reject) {
    admin.database().ref('youtubeChannels/' + ChannelId).once('value').then(function(snapshot){
      uid = snapshot.val().uid
      resolve(uid)
    })
  })
}

function fetchAuthor(uid) {
  var result = [uid]
  return new Promise(function(resolve, reject) {
    admin.database().ref('users/' + uid).once('value').then(function(snapshot){
      result.push(snapshot.val().user)
      resolve(result)
    })
  })
}


fetchUid(ChannelId)
          .then(fetchAuthor)
          .then(function(result){
            console.log("ああああああ uid///////" + result[0])
            console.log("ああああああ video title///////" + VideoTitle)
            console.log("ああああああ author///////" + result[1])
~~~~~~~~~~~~~~
```
こんな感じで、解決しました。

**Comment by karamari** [comment]
```js
uid = snapshot.val().uid
```
`const uid`の間違いでしょうか？
`new Promise`はいらないですね。すでに`.once`が`Promise`を返しますので。
```js
function fetchUid(ChannelId) {
  return admin.database().ref('youtubeChannels/' + ChannelId).once('value').then(function(snapshot){
    return uid = snapshot.val().uid
  })
}

function fetchAuthor(uid) {
  var result = [uid]
  admin.database().ref('users/' + uid).once('value').then(function(snapshot){
    return [uid, snapshot.val().user]
  })
}
```

**Comment by MOTOMUR** [comment]
> const uidの間違いでしょうか？

uidは一つ上の階層で `var uid =""`と定義していたので、そのまま使っていた次第です。なので動いてはいました。
karamarimoさんのコードはいつも見やすいですね。
ありがとうございます。
そのように修正しますね。今のままだと重複が多いので。

> new Promiseはいらないですね。すでに.onceがPromiseを返しますので。

.onceはpromiseを含んでいたのですね。なるほど、ようやく理解できた気がします。

**Comment by karamari** [comment]
> .onceはpromiseを含んでいたのですね。

含むというか返します。
https://firebase.google.com/docs/reference/admin/node/admin.database.Query#once

**Comment by MOTOMUR** [comment]
ありがとうございます。

現在、gaeによる投稿のデバッグをしていたのですが、
https://github.com/MOTOMUR/plz_donation/blob/master/gae-node/app.js
同じ投稿を二度してしまうようになってしまいました。
一度しかやって見ていませんが、二個投稿されてしまうのはまずいです。

この重複を直すために、なんとかしたいのですが、
gaeにて判定を行って重複を避けるべきか、
それとも、firebaseのcloud functionにて監視を行い、
重複したら削除するようにしたほうがいいのでしょうか？

自分的には、投稿してしまう前に判定したほうがいい気がするのでgaeで判定したほうがいいと思うのですが、アイディアが浮かびません。

どうしたらよいでしょう？

**Comment by karamari** [comment]
重複を防ぐというのは、ユーザーが故意に同じ投稿を2回ポストしても無効とするということでしょうか？

**Comment by MOTOMUR** [comment]
gaeによる、youtubeからのfeedによる動画の投稿の重複を避けたいということです。

それは無効にしないようにしたいです。

**Comment by karamari** [comment]
すみません誤解しました。
ユーザーごとに最新の動画の id を保存すればいいのではないでしょうか。

**Comment by MOTOMUR** [comment]
保存してgaeで処理するということですか？

**Comment by MOTOMUR** [comment]
というかそもそも、
https://github.com/MOTOMUR/plz_donation/blob/master/gae-node/app.js
なぜこのコードで二回投稿してしまうのでしょう？？

どうして二回投稿してしまうのか原因わかりますか？

**Comment by MOTOMUR** [comment]
初回がダメだっただけで、二回投稿は毎回確実に行ってしまうわけではなさそうです。

**Comment by MOTOMUR** [comment]
初回がダメだっただけで、二回投稿は毎回確実に行ってしまうわけではなさそうです。

**Comment by karamari** [comment]
インスタンス数は1にしましたか？

**Comment by karamari** [comment]
> 保存してgaeで処理するということですか？

firebase に 最新の動画の id を保存して、GAEにて通知が来た時に id をチェックするということです。

> どうして二回投稿してしまうのか原因わかりますか？

分からないですね...。
