### ISSUE TITLE
ポスト機能の写真を事前アップロードにする。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#28]
ポスト機能を写真のアップロードと同時に投稿するようにしていましたが、事前にアップロードをしてから、投稿ボタンを押せるようにしようとしていたのですが、

progressを可視化するところでつまずいてしまいました。

https://github.com/MOTOMUR/plz_donation/blob/e88c8a190d6af79e3ced5e5a4758ac52829e6195/plz_donation/src/views/MyPage.js#L86-L134

こんな感じで、progressを,

https://github.com/MOTOMUR/plz_donation/blob/e88c8a190d6af79e3ced5e5a4758ac52829e6195/plz_donation/src/views/MyPage.js#L354-L358

こうしたのですが、stateだと、同期が取れず、うまく表示ができません。
こういう時どうしたらよいでしょう？

**Comment by karamari** [comment]
同期が取れない、うまく表示できないとはどういうことでしょうか？

**Comment by karamari** [comment]
https://github.com/MOTOMUR/plz_donation/blob/e88c8a190d6af79e3ced5e5a4758ac52829e6195/plz_donation/src/views/MyPage.js#L97-L100

これだとうまく行かないと思うんですが、なぜだか分かりますか？

**Comment by MOTOMUR** [comment]
条件文にstateを用いると、最初しか判定しない。。ですかね？

アップロード前と後はprogressを消そうと思っていじったのですが。
どのようにしたらいいのでしょうか？

**Comment by MOTOMUR** [comment]
> 同期が取れない、うまく表示できないとはどういうことでしょうか？

１００％に近くにつれて、円になって行くように書いたつもりですが、最初の状態のまま写真が表示されてしまいます。

**Comment by MOTOMUR** [comment]
```
var progress =(snapshot.bytesTransferred / snapshot.totalBytes) * 100
        for(var i = 0; i<=100; i=progress){
          if(i<100){
            self.setState({progress : progress})
          }else{
            self.setState({postPush:false})
          }
        }
```
この書き方やってみたんですが、ループ抜けられなくてダメみたいですね。。

**Comment by karamari** [comment]
for 文の書き方がまず間違ってますが、なぜ for 文を使おうとしたんでしょうか？
そのコードの意味がよく分からないです。

> 条件文にstateを用いると、最初しか判定しない。。ですかね？

最初というのがよくわからないですが、私が言いたかったのは`.setState`は非同期に`state`を更新するので、

https://github.com/MOTOMUR/plz_donation/blob/e88c8a190d6af79e3ced5e5a4758ac52829e6195/plz_donation/src/views/MyPage.js#L97

の直後では`state.progress !== progress`だということです。

> 最初の状態のまま写真が表示されてしまいます。

最初の状態とは何ですか？円が全く表示されないということですか？

`uploadTask.on()`の第二引数の関数はデータが少しずつ送られる度に呼び出されるんですが、ご存じでしたか？

**Comment by MOTOMUR** [comment]
> 最初の状態とは何ですか？円が全く表示されないということですか？

円のカケラだけ表示されて、そのまま消えて写真が表示されてしまいます。
（説明がわかりづらいと思うので、deployしてあるので理解できない場合は、そちらを見てもらえると助かります。）

> for 文の書き方がまず間違ってますが、なぜ for 文を使おうとしたんでしょうか？

stateの更新は非同期的なので、stateによって条件分岐し、擬似的に同期的に動いてるようにしようと思ってこうしました。（非同期でも、stateのprogressが１００になった段階でもう一度ifを通ると思ったので。）
コードの中の説明としては、１００になるまではprogressを表示したく、１００になったら消したいという気持ちのままに書いたって感じです。（行けると思ったのですがダメでしたね。）

for文の第３引数がおかしいのだと思いますが、iはprogressと同期したかったのです。

> uploadTask.on()の第二引数の関数はデータが少しずつ送られる度に呼び出されるんですが、ご存じでしたか？

すでに（％表記）可能な例のコードがあったため、あまり仕様を見ずに使っていたので知りませんでした。

**Comment by karamari** [comment]
> stateの更新は非同期的なので、stateによって条件分岐し、擬似的に同期的に動いてるようにしようと思ってこうしました。（非同期でも、stateのprogressが１００になった段階でもう一度ifを通ると思ったので。）

> for文の第３引数がおかしいのだと思いますが、iはprogressと同期したかったのです。

すみません意味が分からないです...。
同期するとはどういうことでしょうか？
for 文でぐるぐるループしてる間に progress が変わるということはあり得ないですよ。

**Comment by karamari** [comment]
> deployしてあるので理解できない場合は、そちらを見てもらえると助かります

マイページの作成でエラーが出るのでpostできないですね..。

**Comment by MOTOMUR** [comment]
> マイページの作成でエラーが出るのでpostできないですね..。

そうでした。。それ以前の問題でしたね。。。。
とりあえずルールの改訂に尽力します。。。 かなり五里霧中ですが。。。

> for文でぐるぐるループしてる間に progress が変わるということはあり得ないですよ。

そういえば、for文の前にすでにvar progressの値は決まってしまうんでしたね。
グローバル変数での処理も考えたのですが、その場合、jsxの
https://github.com/MOTOMUR/plz_donation/blob/e88c8a190d6af79e3ced5e5a4758ac52829e6195/plz_donation/src/views/MyPage.js#L354-L358
この部分がリセットされないですよね？？
どのようにしたらいいでしょうか。。

**Comment by karamari** [comment]
なぜグローバル変数なんでしょうか？

`setState`の直後に`state`を取得してるのが問題なのであって、`state`から取得せずにそのまま`progress`を使えばいいのでは？
```js
      var progress =(snapshot.bytesTransferred / snapshot.totalBytes) * 100 
       self.setState({progress : progress}) 
       if(progress===100){ 
         self.setState({postPush:false}) 
       } 
```
もっとも、三項演算子を使ったほうがいいと思いますが。

**Comment by karamari** [comment]
そもそも`progress`が`100`に到達する保証があるのか分からないので、アップロード完了時のコールバックの方で`self.setState({postPush:false}) `をしたほうがいいと思います。

**Comment by karamari** [comment]
docs はご覧になりましたか？
https://firebase.google.com/docs/reference/js/firebase.storage.UploadTask#on

**Comment by MOTOMUR** [comment]
そういえば動作完了時のコールバックがありましたね。失念していました。ありがとうございます。
