### ISSUE TITLE
謎のログのwarming

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#29]
`The SSL certificate used to load resources from https://adm.shinobi.jp will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.`
こやつはなんでしょう。。？

**Comment by MOTOMUR** [comment]
ん。httpの部分は忍者アドセンスの部分ですね。

**Comment by karamari** [comment]
調べたところシマンテックのSSL証明書が chrome で向こうになる予定らしいです。
https://adm.shinobi.jp が対処しない限りどうしようもないと思います。

**Comment by MOTOMUR** [comment]
なるほどです。ありがとうございます。
