### ISSUE TITLE
youtubeAPIについて相談です。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#31]
youtubeAPIの確認のため、動画アプリを触る機会があったのですが、
API系でよくみるこのような認証の方法で、ユーザーの登録を促すことはできないでしょうか？
（youtubeなどの外部APIとの接続の話です！）

<img width="654" alt="2017-12-29 21 00 06" src="https://user-images.githubusercontent.com/30742628/34436695-687fecf6-ecdb-11e7-988d-db7d382016d6.png">

**Comment by karamari** [comment]
たぶんこれだと思います。
https://developers.google.com/youtube/v3/guides/auth/client-side-web-apps

その画面はおそらく step 3 の Google Prompt だと思います。

**Comment by MOTOMUR** [comment]
なるほど。大変そうですね。

というか。最新の投稿の情報を得ることはできなさそうですね。残念です。
