### ISSUE TITLE
svgの扱いについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#32]
https://github.com/MOTOMUR/plz_donation/blob/4617bd4de2bce5e53b3d61d86fbe613994a1a941/plz_donation/src/views/GettingStarted.js#L56
ロゴを作って見たので、表示して見たく、色々調べて見てやって見ていたのですが、表示できず、altが表示されてしまいます。。。

.htaccessも設定して見ましたが。。。

どうしたら表示できますかね？？

**Comment by MOTOMUR** [comment]
また、似たような問題で申し訳ないんですが。AppBarのログインログアウトボタンがずれちゃうんですが、なんでなのでしょう。。。。＞＜

**Comment by karamari** [comment]
ずれるとはどういうことでしょうか？

**Comment by karamari** [comment]
img についてですが、import しましたか？
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files

**Comment by MOTOMUR** [comment]
imgの使い方を勘違いしていました。ありがとうございます。

こんな感じでずれてしまいます。
<img width="365" alt="2017-12-30 2 05 08" src="https://user-images.githubusercontent.com/30742628/34442858-6fe02c90-ed08-11e7-8b2d-8b7257a22486.png">

**Comment by karamari** [comment]
`vertical-align: super`にすると直りますが...もっといい方法があるかもしれません。

**Comment by MOTOMUR** [comment]
IconButtonが並びの最上層だったので、そこにスタイル指定すると行けました。ありがとうございます！
