### ISSUE TITLE
GettingStartedにて、backgroundなどのCSS設定の問題。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#34]
主にCSS関連の問題なのですが、
背景画像を作成して、表示させようとしているのですが、
https://github.com/MOTOMUR/plz_donation/blob/1c82bd7b0aed87cad589b20013e69ea2c8f0ef3c/plz_donation/src/views/GettingStarted.js#L45-L58
こんな感じでごり押ししないと、背景画像が下まで表示されず、格好悪くなってしまいます。

縦横比計算して、styleをたくさん指定しているところにpaddingTopで入れても見たのですが、その場合は、背景表示がうまくいってもdivの中身ごと出てしまうので、どのように縦横比を維持した状態で表示したら良いかわかりません。

ちなみに作成した画像はレスポンシブなはずなので、ある程度の大きさ変更は大丈夫だと思います。

`backgroundSize:'auto 100%'`だと、横幅がうまくいかなかったりと、簡単なところは大体試しました。

それに追加で困っていることなのですが、その設定に困っている背景画像を使っているところに、ロゴをレスポンシブに上下左右中央に配置し、その下に、「さあ、始めよう。」と登録ボタンを中央揃えで表示し、
そのロゴの横にロゴからボタンの表示いちの上下中央に表示するようにしたいのですが、色々検索して見ましたが、うまく作れる気がしません。
<img width="1631" alt="2018-01-05 0 02 29" src="https://user-images.githubusercontent.com/30742628/34569323-c429f932-f1ab-11e7-91da-6c3a79e0c33d.png">

背景の縦横比はうまくいってませんが、こんな感じで、このロゴの横に説明を書く予定です。

**Comment by MOTOMUR** [comment]
このページはレスポンシブじゃなくてもいいのですかね？
レスポンシブに綺麗な配置するの難しいですよね。
どう思いますか？？

**Comment by karamari** [comment]
> そのロゴの横にロゴからボタンの表示いちの上下中央に表示するようにしたい

ここがよく分からないですね。

背景の高さはどうしたいのでしょうか？数字で指定してもいいと思いますが。

上下左右中央にするには flexbox を使えばいいです。

**Comment by karamari** [comment]
> このページはレスポンシブじゃなくてもいいのですかね？

レスポンシブとは具体的にどこがどうなることですか？

**Comment by MOTOMUR** [comment]
> 背景の高さはどうしたいのでしょうか？数字で指定してもいいと思いますが。

背景画像として作成したところまで表示したいです。普通に数字指定でいいんですね。そうして見ます。

> ここがよく分からないですね。

<img width="1071" alt="2018-01-05 12 41 41" src="https://user-images.githubusercontent.com/30742628/34594672-d1496a66-f215-11e7-89ae-d254f713bbed.png">
こんな感じで配置したいのですが、このロゴの位置上下左右中央指定（absolutely）と、説明をロゴとボタンを含めたコンテナの上下中央に配置したいのです。

> レスポンシブとは具体的にどこがどうなることですか？

画面幅を小さくした時に背景と、ロゴとボタンと説明文を綺麗に配置することですね。
まあ多分画面幅８００以下は別のスタイルにしないと綺麗にはならなそうですが。
背景画像を％で指定できないと、画面幅８００以上の時の背景と説明文とロゴの位置と大きさがうまく扱えない気がするのですが、どうでしょうか？

画面幅が許す限りは、スクショのような形で表示したいです。

**Comment by karamari** [comment]
> 背景画像として作成したところまで表示したいです。

いえ、どこまで表示するかではなく、実際の高さのことです。
ロゴを上下左右中央にするというのは、背景の高さに対して中央ということですよね？

ロゴは背景に対して中央でありながら、説明文はロゴとボタンに対して中央というのは難しいと思います。

**Comment by MOTOMUR** [comment]
> ロゴは背景に対して中央でありながら、説明文はロゴとボタンに対して中央というのは難しいと思います。

そうなのですね。

> 実際の高さのことです。

`viewBox="0 0 1366 768"`これですかね？　


> ロゴを上下左右中央にするというのは、背景の高さに対して中央ということですよね？

そうです。

**Comment by karamari** [comment]
> `viewBox="0 0 1366 768"`これですかね？　

いえ、私がお聞きしたのは、背景の高さをどうしたいかということです。
1000pxですか？子要素に合わせますか？ブラウザの高さに合わせますか？
ブラウザの高さに合わせるなら広告が画面外下に隠れる形になりますがそれでいいのでしょうか？

------------

ロゴとボタンを上下左右中央にするならできます。
[demo](https://jsfiddle.net/karamarimo/pfpmmcx2/1/)

**Comment by MOTOMUR** [comment]
> ブラウザの高さに合わせるなら広告が画面外下に隠れる形になりますがそれでいいのでしょうか？

ブラウザの高さにしたいです。広告は隠れて構いません。
ロゴも背景にしちゃったらできないですかね？

**Comment by karamari** [comment]
こんな感じですかね。
[demo](https://jsfiddle.net/karamarimo/pfpmmcx2/2/)

**Comment by MOTOMUR** [comment]
そのようにして見て、デプロイしたのですが、画面幅が大きい時は、背景がうまく表示しきれません。
pushもしておきますね。

また、横のテキストも、画面超えた右に表示されてしまいます。

**Comment by MOTOMUR** [comment]
ちょっとミスってて、直しました。
横幅は合うようにになったのですが、縦が短くなってカッコ悪いです。
色々いじって見ますが、うまくいくかは微妙です。頑張ります

**Comment by MOTOMUR** [comment]
ある程度まではうまくいったので、デプロイしました。
GettingStarted.jsにて、`window.matchMedia('(min-width:1300px)').matches`を用いて、表示を変えたいのですが、読み込み時にしか作用しないので、ウィンドウ幅を変えた時にレスポンシブではありません。
https://qiita.com/r_abe01/items/a3a2e94b5162d949037b#windowmatchmedia%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E5%88%A4%E5%AE%9A
この記事のものだと、変更をロードしてそうなのでこれを使ったらできそうですが、
render内で
```
{
              (window.matchMedia('(min-width:1300px)').matches)
               ?<div id="side">
                  <h2 style={{position:'absolute',top:'8%',textAlign:'center',marginLeft:'30px'}}>{strings.title}</h2>
                  <p style={{position:'absolute',top:'40%',textAlign:'center',lineHeight: '300%',textAlign: 'justify'}}>{strings.explanation}</p>
                </div>
               :<div>/*何か別の表示*/</div>
             }
```

こうしたいので、コードを参考にできる気がしなかったので、質問させていただきました。
stateに入れて判定しようかとも思いましたが、何かいい方法ないでしょうか？

**Comment by MOTOMUR** [comment]
それと、`opacity`と`transition`や`animation`などを用いて、背景が不透明度をあげてくように作りたいのですが、調べて色々やって見ましたが、難しいです。

予定している動作は、

背景と、ロゴは不透明度を下げるフェードイン（タイミングずらす）
タイトル、説明、ボタンは右からスライドイン（タイミングずらす）
順番としては、
背景→→→ロゴ→→→タイトル→説明→ボタン（→で時間差の大体のイメージを示しています。）

右からスライドインはこれから頑張ってみようと思いますが、どうしても`opacity`をいじるのが難しいので、アドバイスもらえたら助かります。

**Comment by karamari** [comment]
> stateに入れて判定しようかとも思いましたが、何かいい方法ないでしょうか？

js ではなく css でやればいいのでは？
[メディアクエリの利用 - MDN](https://developer.mozilla.org/ja/docs/Web/CSS/Media_Queries/Using_media_queries)

**Comment by MOTOMUR** [comment]
確かにその方がいいですね。

少しやってみたいビューの設定もありましたが、代用でやってみようとおもいます。

**Comment by karamari** [comment]
> これをbackgraund-imageに適応したいですが、できないですよね？どのようにしたらいいのでしょうか？

普通にその`opacity-fade-in`を使えばいいと思うのですが...。

**Comment by karamari** [comment]
background image だとなにか変なことが起こるんだろうかと思って試してみましたが、普通にできましたよ。

https://jsfiddle.net/karamarimo/c5mL5rab/

**Comment by MOTOMUR** [comment]
ほんとですね。。。

最初にアニメーションの設定してる時、上位のstyleに設定すると、全て同じアニメーションしか反映されなかったので、できないのかと思いました。
ありがとうございます。
