### ISSUE TITLE
howToUseの画面のUIについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#36]
howToUseにて、ボタンによって、表示する内容を変化しようと、ボタンを作成して、押されたボタンの内容が表示される、というように作りたかったのですが、
<img width="247" alt="2018-01-06 23 22 14" src="https://user-images.githubusercontent.com/30742628/34640576-7367784c-f338-11e7-8fe1-0a70df8ca626.png">
本当はこのようなボタンが作成されるはずなのですが、stateの三項演算子で分岐させたら、表示が変になりました。
<img width="214" alt="2018-01-06 23 23 06" src="https://user-images.githubusercontent.com/30742628/34640584-94980bf8-f338-11e7-8795-f2d79f8bd944.png">
（該当部は全てボタンです。）

問題のコードはこちらです。
https://github.com/MOTOMUR/plz_donation/blob/master/plz_donation/src/views/Buttons.css

https://github.com/MOTOMUR/plz_donation/blob/22f33d934f2321952449a61206a96e31c4bb675c/plz_donation/src/views/howToUse.js#L50-L64

ボタンの元々の動作を確認するなら、デプロイされているので、gettingStartedの新規登録ボタンの動きを参照してください。howToUseでのそれらは色違いのものです。
説明文が表示されているボタンの部分はホバー時のボタンの状態にしようと思い、このようなコードになりました。

どのようにしたら修正できるのでしょう。教えてください。

**Comment by karamari** [comment]
新規登録のボタンと同じ見た目にしたいということですか？

**Comment by MOTOMUR** [comment]
新規登録ボタンと同じ見た目にしたいということです。

> 表示が変とはどういうことですか？

新規登録ボタンと同じCSSコードを書いてあるのですが、先ほどのコメントの２個目の写真のようになってしまいます。

**Comment by karamari** [comment]
css を見ると重複が多いのが気になります...。共通している部分は`.button`にまとめてすべてのページで共用するとかしたほうがいいと思いますよ。button1, 2, 3 ではなく descriptive な名前を付けたほうがいいですよ。

border がないのは`border-style`を指定していないからですね。
padding もないです。

気になるのが、`::before`や`::after`はなんのためにあるんでしょうか？ホバー時に`line-height: 40px;`としているのはなぜでしょうか？

**Comment by MOTOMUR** [comment]
詳しいことはわかっていませんが、重複を避けるために、まとめてしまったことで、うまく表示できなかったようです。なので全て別に作りました。

stateで表示の判定をしており、再描画してしまうため、ボタンのアニメーションが起こってしまい、ボタンがいない時間帯が存在してしまうのですが、このようにならないアイディアありますでしょうか？

**Comment by karamari** [comment]
> stateで表示の判定をしており、再描画してしまうため、ボタンのアニメーションが起こってしまい、ボタンがいない時間帯が存在してしまうのですが、このようにならないアイディアありますでしょうか？

アニメーションをcssではなくjsで行うという手もあります。
timeline ベースのアニメーションができるライブラリはいくつかあります。
[anime.js](http://animejs.com/) 
[timelinelite](https://greensock.com/timelinelite)

**Comment by MOTOMUR** [comment]
ありがとうございます。
