### ISSUE TITLE
ファイルの違う受け渡しでのarrow functionの扱いについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#4]
PostRef4LatestUserにて
onClick={()=>this.props.herfUserPage(this.props.post.uid)}
この引数を
Homeで
<PostRef4LatestUser
                              post={latest_post}
                              myuid={this.state.userId}
                              herfUserPage={this.herfUserPage.bind(this)} />
このように受け取り
herfUserPage=(val)=>{
    this.props.history.push('/userPage/' + val)
  }
こういうように処理させているのですが、この場合、onClickにallowを入れないように書きたいですが、どのようにしたら良いでしょう。
とりあえずherfUserPageは現在のgitのコードではarrowではなかったので修正したので、postRef4LatestUserのbind(this)はいらないようにはなっています。onClickのarrowは如何に消せるでしょう。

**Comment by karamari** [comment]
コードは```で囲むといい感じになります。
```js
onClick={()=>this.props.herfUserPage(this.props.post.uid)}
```
ここのことでしょうかね。
https://github.com/MOTOMUR/plz_donation/blob/821262cf5d96654e38bc9c18d91f1fbeb23c973b/src/views/components/PostRef4LatestUser.js#L120

PostRef4LatestUser 内でハンドラーを作ればいいのではないでしょうか。
```js
handleHeaderClick = () => {
  this.props.herfUserPage(this.props.post.uid)
}
// ...
onClick={this.handleHeaderClick}
```

**Comment by MOTOMUR** [comment]
一つの関数をクッションにしたらいいのですね。ありがとうございます。
