### ISSUE TITLE
フィードバックを受ける方法について相談です。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#42]
フィードバックを受診するように設定したく、とりあえずサイト用にemailアカウントを作り、掲示する、といった方法を取っています。

もっと賢くフィードバックを受け取る方法ってありますでしょうか?

**Comment by karamari** [comment]
フィードバックのフォームを react app 上で作るという手もあります。

**Comment by MOTOMUR** [comment]
ユーザーサイドから考えると、react appの方がめんどくささが少なくなって多くのレスポンスが望めそうですよね。

ありがとうございます。あまりにもフィードバックが少なかった時に考えようと思います。
