### ISSUE TITLE
PostRef4LatestUserのスターボタン表示について。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#5]
現在の時点でコードの原因か描画の重さによる表現不可能であるのか原因は不明ですが、コードである可能性もあるのですが、

スターボタンが全てSTARされてない状態となります。
コード上のミスであれば教えていただけると助かります。
https://github.com/MOTOMUR/plz_donation/blob/de38dc7e2911da9fb342e902ffc5387c61013710/src/views/components/PostRef4LatestUser.js#L159

https://github.com/MOTOMUR/plz_donation/blob/master/src/views/components/StarBtn.js

**Comment by karamari** [comment]
原因を見つけるには、実行してみて変数の値がどうなっているかをチェックするのが一番速いと思います。

react の dev tools でStarBtnやPostRef4LatestUserに渡されているpropsの値を確かめてみてください。

また、スターされているかどうかの判定はStarBtnではなくPostRef4LatestUserでしたほうがいいと思います。
StarBtnは presentational component としてなるべく簡単に、再利用性が高いように作ったほうがいいからです。

**Comment by MOTOMUR** [comment]
スターボタンをpresentational component として再作成しました。そのため、starredBtnも作成しました。
propsの値を確かめようと思ったのですが、
https://github.com/MOTOMUR/plz_donation/blob/21ff94b0a5a1c154bea0902f91bc0354ccf1fe2c/src/views/components/PostRef4LatestUser.js#L37
そもそもここにてfirebaseのrefを走らせ、stateのstarとしてデータベースのuserStarを保存していたので、こちらをrender内でconsole.logを走らせて見たのですが、初期の数回はstateの中身は空で、その後は出てくるのですが、どうやら描画時の判定に間に合っていないようです。
https://github.com/MOTOMUR/plz_donation/blob/21ff94b0a5a1c154bea0902f91bc0354ccf1fe2c/src/views/components/PostRef4LatestUser.js#L162

**Comment by karamari** [comment]
> 初期の数回はstateの中身は空で、その後は出てくるのですが、どうやら描画時の判定に間に合っていないようです。

コンポーネントが作成されてから非同期にデータを取得しているので、当然作成直後にデータはないですね。

> stateの判定を待ってからrenderの処理をさせたらいいのでしょうか？

いえ、`state`が更新されれば自動的に表示も更新されるので、そのままでも問題ないと思います。

Reactはデフォルトでは`setState`が実行されるか`props`が変化するたびに`render`関数が実行され、表示が更新されます。

**Comment by MOTOMUR** [comment]
自分のプロジェクトのfirebaseで稀によくあるちゃんとデータ送ってくれない病だったっぽいです。一回変えて戻したら色々治りました。git pushします。相談に乗っていただきありがとうございます。
