### ISSUE TITLE
syntaxの致命的でないwarning

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#7]
1. 
ずっと放置していたのですが、
`./src/views/makeMyPage.js
  Line 30:   Expected a default case  default-case
  Line 131:  Expected a default case  default-case
  Line 143:  Expected a default case  default-case`
このような感じで、default caseを求められているところがたくさんあるのですが、特に何か作りたくない場合のdefault caseの中身をどうしたらいいのかわからず、困っています。

2. 
`./src/views/components/StarBtn.js
  Line 6:  Useless constructor  no-useless-constructor`
これはstarredBtnでもそうなのですが、なんのことでしょうか？
意味がわからず放置しています。

3. 
firebaseのアップデート関数の話なのですが、
`./src/views/components/PostRef4LatestUser.js
  Line 59:  'updates' is already defined`
このように言われているのですが、これを外して、一つ上の階層でつけるのは、それはそれでまずい気がして放置しているのですが、どうしたら治るでしょうか？

**Comment by karamari** [comment]
1. エラーを投げるか適当に`<div></div>`を返すかすればいいのでは？

1. `constructor`ではスーパークラスの`constructor`を呼び出しているだけなので、overrideする意味がないということです。
https://github.com/MOTOMUR/plz_donation/blob/cffae62076541eb1a3218b2bb0ef2ebd53776c34/src/views/components/StarBtn.js#L6-L8
ESLintの警告ですよね？設定でOFFにしてもいいのではないでしょうか。

1. `var updates`と`..ref().update`を`if`の外に出せばいいのでは？

**Comment by karamari** [comment]
> updateに関しては、return firebase.ref が同期的に中身を得てから実行するかどうか不安なので、外に出すのはやめておこうと思います。。。

どういうことでしょうか？
`if`の外に出しても機能的には何も変わらないと思いますが。

**Comment by MOTOMUR** [comment]
なるほど、この場合は大丈夫なのですね。
少しわからなくなってきたことがあるので、質問させていただきます。
今回のように、処理順を気にしなくても大丈夫なパターンと、気にしなければならないパターン（fetchPost系の別関数の処理順）があると思うのですが、
今回のように同一関数上での処理はコードの書いた順に処理されるのが保証されているのでしょうか？
そして、別関数の処理順は保証されていないのでしょうか？

**Comment by karamari** [comment]
私が意図したのはこれを

https://github.com/MOTOMUR/plz_donation/blob/cffae62076541eb1a3218b2bb0ef2ebd53776c34/src/views/components/PostRef4LatestUser.js#L52-L64

このようにしても何も変わらないと言うことです。非同期・同期とは関係ありません。

```js
const updates = {} 
if (starData.stars&&starData.stars[myUserId]) { 
  updates['users/' + starUserData + '/userStar/stars/' + myUserId]= null 
  updates['users/' + starUserData + '/userStar/starCount']= starData.starCount-1 
  updates['users/' + myUserId + '/starred_users/' + starUserData]= null 
} else { 
  updates['users/' + starUserData + '/userStar/stars/' + myUserId]= true 
  updates['users/' + starUserData + '/userStar/starCount']= starData.starCount+1 
  updates['users/' + myUserId + '/starred_users/' + starUserData]= true
}
return firebase.database().ref().update(updates) 
```

> 同一関数上での処理はコードの書いた順に処理されるのが保証されているのでしょうか？

保証されています。
例えば次のようなコードのとき、

```js
const x = 3
asyncFunc1(x)  // 非同期処理1
asyncFunc2(x)  // 非同期処理2
```
以下の事が保証されます。

1. `asyncFunc1` 、`asyncFunc2`が実行される前に`x=3`となる
1. `asyncFunc2`が処理を開始する前に`asyncFunc1`が処理を開始する

非同期処理の場合は保証されるのは開始する順番だけで、いつ何をしていつ終わるかは全く分かりません。

> 別関数の処理順は保証されていないのでしょうか？

関数がどのように呼び出されるかに依存します。

**Comment by MOTOMUR** [comment]
ありがとうございます！理解できました！

**Comment by MOTOMUR** [comment]
今後もsyntax waringはあると思いますが、当面ないと思うので一度閉じます。
