### ISSUE TITLE
Home画面のperformanceについて。

### ISSUE THREAD

**Issue by MOTOMUR** [MOTOMUR/plz_donation#8]
<img width="1477" alt="2017-11-28 1 13 54" src="https://user-images.githubusercontent.com/30742628/33276668-8b97fe1a-d3d9-11e7-9793-b2c788a9fcc3.png">
こちらはhomeへの最初のアクセス時のパフォーマンス（build前）なのですが、
idol timeが多めに取られていると思うのですが、主にこれは何が原因で長いのでしょうか？？それとも元々このくらい取る仕様なのでしょうか？

今後、サイトのスピードを検証する時はbuild後のperformanceで検証した方がいいのでしょうか？

**Comment by karamari** [comment]
idle time は html や js をリクエストして到着するまで待っている時間だと思います。
Network のとこで getAccountInfo や profile_image が時間がかかっているのが気になりますね。
真ん中あたりで何もしてない時間が存在するのも不思議です。

react devtools を使っていますか？
たぶん違うと思いますがもしかしたらそれが遅さの原因かもしれません。
一度無効にしてみてください。

**Comment by MOTOMUR** [comment]
返信が遅れました。生活が多忙だったため遅い返事申し訳ありません。

とりあえず、build後のパフォーマンスが気になったのでビルドして、確認してみました。
build後のパフォーマンスは
<img width="1477" alt="2017-11-28 1 13 54" src="https://user-images.githubusercontent.com/30742628/33416199-9bd36a9c-d5de-11e7-99d5-90c9879fc5fb.png">

このようになっているので、idol timeはとりあえずは短くなりました。
いまだに何もしないidol timeは気になりますね。

karamarimoさんが指摘してくれたreact devtoolsですが、無効にする操作を検索してみてたのですが、いまいち方法が見つからなくて、どうしたらいいでしょうか？

**Comment by karamari** [comment]
別に返信は急がないでいいですよ。

chrome でしたら、URL
chrome://extensions/
に移動して、React Developer Tools を探し、「有効」のチェックを外せばいいです。

スクショだとあまりよく分からないですね。
ご自分でもう少し詳しく見ていただくか、デプロイしていただければ、こちらでも試してみますよ。
正直私も使い慣れていないので原因が発見できるかは分からないですが。

**Comment by karamari** [comment]
追記ですが、

[Profiling Components with the Chrome Performance Tab](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab)
[Debugging React performance with React 16 and Chrome Devtools](https://building.calibreapp.com/debugging-react-performance-with-react-16-and-chrome-devtools-c90698a522ad)

ここを見る限り development mode で実行する必要がありますね。
また、コンポーネントのイベントが User Timing のところで見れるみたいです。

`react-scripts build`は production mode でビルドするので、それだと無理ですね。

**Comment by MOTOMUR** [comment]
> 別に返信は急がないでいいですよ。
ありがとうございます。react dev toolは外せました。

deployは最新のものですので、気が向いたらお願いします。

> development mode で実行する必要がありますね。
devmodeというのは、何か別のビルドを用いたら良いということでしょうか？

**Comment by karamari** [comment]
`react-scripts start` だと dev mode で実行されます。
しかしビルドしたファイルが出力されることはありません。
dev mode で出力するコマンドは現在ないようです。

デプロイしていただいたもので Home を開いてみましたが、別に重いという印象はありませんが...。

**Comment by karamari** [comment]
Home の Latest Posted Users のことでしょうか？
画像の読み込みに0.5秒くらいかかるだけで(10個同時に読み込むので当然)、それ以外はほぼ一瞬で表示されます。

**Comment by MOTOMUR** [comment]
> Home の Latest Posted Users のことでしょうか？

そうです。
なるほど。同時に読み込みで遅延するのは当たり前なのですね。ありがとうございます。
しばらく遅延での致命的な問題が起こるまで、どちらもクローズして置きます。
